apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: myapp/api:v1  # Θα δημιουργήσουμε αυτή την εικόνα
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-headless:27017/myapp
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONPATH
          value: /app
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: api-config
          mountPath: /app/config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 6
      volumes:
      - name: api-config
        configMap:
          name: api-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0