apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-logs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/api-logs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi