apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  jwt-secret: your_jwt_secret_here

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
stringData:
  root-username: admin
  root-password: your_secure_password_here